name = "gleamstral_examples"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "Examples for the Gleamstral library"
repository = { type = "github", user = "Neofox", repo = "gleamstral", path = "examples" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleamstral = { path = "../" }
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glenvy = ">= 1.2.0 and < 2.0.0"
file_streams = ">= 1.4.0 and < 2.0.0"
gleam_json = ">= 2.3.0 and < 3.0.0"
gleam_httpc = ">= 4.1.0 and < 5.0.0"
